
@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc0NDEwNDk0NywiZXhwIjoxNzQ0MTkxMzQ3fQ.A9-3yeBX26B1WA54HwjXllqmMeGMzlNom_yQXiKVQgA
### Test User Login
POST http://localhost:8080/api/auth/signin
Content-Type: application/json

{
    "username": "testuser",
    "password": "testpassword"
}

### Test Admin Login
POST http://localhost:8080/api/auth/signin
Content-Type: application/json

{
    "username": "admin",
    "password": "adminpassword"
}

### Test User Registration
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
    "username": "newuser",
    "email": "newuser@example.com",
    "password": "newpassword",
    "role": ["ROLE_USER"]
}

### Test Admin Registration
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
    "username": "admin",
    "email": "admin@example.com",
    "password": "adminpassword",
    "role": ["ROLE_ADMIN"]
}

### Test Registration with Multiple Roles
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
    "username": "moderator",
    "email": "moderator@example.com",
    "password": "modpassword",
    "role": ["ROLE_MODERATOR"]
}

### Test Registration with Invalid Role
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
    "username": "invalidrole",
    "email": "invalid@example.com",
    "password": "invalidpassword",
    "role": ["invalid"]
}

### Test Registration with Duplicate Username
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
    "username": "testuser",
    "email": "duplicate@example.com",
    "password": "duplicatepassword",
    "role": ["user"]
}

### Test Registration with Duplicate Email
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
    "username": "duplicateemail",
    "email": "testuser@example.com",
    "password": "duplicatepassword",
    "role": ["user"]
}

###Get All
GET http://localhost:8080/api/test/all
Authorization: Bearer {{token}}
Content-Type: application/json

###Get User
GET http://localhost:8080/api/test/user
Authorization: Bearer {{token}}
Content-Type: application/json

###Get Moderator
GET http://localhost:8080/api/test/mod
Authorization: Bearer {{token}}
Content-Type: application/json

###Get Admin
GET http://localhost:8080/api/test/admin
Authorization: Bearer {{token}}
Content-Type: application/json

### Get All Novels
GET http://localhost:8080/api/novels
Authorization: Bearer {{token}}
Content-Type: application/json

### Get Novel by ID
GET http://localhost:8080/api/novels/1
Authorization: Bearer {{token}}


### Create Novel
POST http://localhost:8080/api/novels
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "title": "New Novel",
    "author": "John Doe",
    "description": "A new novel description.",
    "publishedDate": "2023-10-01"
}

### Get Chapters by Novel ID
GET http://localhost:8080/api/chapters/novel/1
Authorization: Bearer {{token}}
Content-Type: application/json
### Get Chapter by ID
GET http://localhost:8080/api/chapters/1
Authorization: Bearer {{token}}
Content-Type: application/json

### Get Chapter by Novel ID and Chapter Number
GET http://localhost:8080/api/chapters/novel/1/chapter/1
Authorization: Bearer {{token}}
Content-Type: application/json